2025-05-27 16:07:02,964 - AkilliEvOtomasyonu - INFO - Akilli Ev Otomasyon Sistemi baslatiliyor
2025-05-27 16:07:02,967 - AkilliEvOtomasyonu - INFO - Veri simülasyonu başlatılıyor
2025-05-27 16:07:02,967 - VeriUretimi - INFO - 3 gün için veri üretiliyor...
2025-05-27 16:07:03,132 - VeriUretimi - INFO - Veri seti c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\data\raw\generated_data_20250527_1607.csv konumuna kaydedildi.
2025-05-27 16:07:03,133 - AkilliEvOtomasyonu - INFO - Model eğitimi başlatılıyor
2025-05-27 16:07:03,133 - ModelEgitimi - INFO - ML modelleri eğitiliyor: c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\data\raw\generated_data_20250527_1607.csv
2025-05-27 16:07:03,426 - ErrorHandler - ERROR - Beklenmeyen hata: cannot access local variable 'y_train_dict' where it is not associated with a value in train_models
2025-05-27 16:07:03,457 - ErrorHandler - ERROR - Traceback (most recent call last):
  File "c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\src\utils\error_handling.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\app.py", line 115, in train_models
    model_manager.train_models_for_all_devices(data_path, model_type='random_forest', optimize=optimize)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\src\models\model_manager.py", line 40, in train_models_for_all_devices
    X_train, X_test, y_train_dict, y_test_dict, preprocessor = process_raw_data(
                                                               ~~~~~~~~~~~~~~~~^
        csv_path, save_processed=True
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\src\data_processing\preprocessing.py", line 546, in process_raw_data
    return processor.process_data(csv_path, save_processed, output_dir)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\src\data_processing\preprocessing.py", line 418, in process_data
    X_train, X_test, y_train_dict, y_test_dict = self.split_data(X, targets)
                                                 ~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\src\data_processing\preprocessing.py", line 303, in split_data
    y_train_dict[first_target] = y_train_first
    ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'y_train_dict' where it is not associated with a value

2025-05-27 16:07:03,457 - AkilliEvOtomasyonu - ERROR - Uygulama hatası: Beklenmeyen hata: cannot access local variable 'y_train_dict' where it is not associated with a value
