2025-05-27 15:41:08,635 - AkilliEvOtomasyonu - INFO - Akilli Ev Otomasyon Sistemi baslatiliyor
2025-05-27 15:41:08,636 - AkilliEvOtomasyonu - INFO - Veri simülasyonu başlatılıyor
2025-05-27 15:41:08,637 - VeriUretimi - INFO - 3 gün için veri üretiliyor...
2025-05-27 15:41:08,795 - VeriUretimi - INFO - Veri seti c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\data\raw\generated_data_20250527_1541.csv konumuna kaydedildi.
2025-05-27 15:41:08,795 - AkilliEvOtomasyonu - INFO - Model eğitimi başlatılıyor
2025-05-27 15:41:08,795 - ModelEgitimi - INFO - ML modelleri eğitiliyor: c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\data\raw\generated_data_20250527_1541.csv
2025-05-27 15:41:08,796 - ErrorHandler - ERROR - Beklenmeyen hata: 'SmartHomeDataProcessor' object has no attribute 'read_data' in train_models
2025-05-27 15:41:08,800 - ErrorHandler - ERROR - Traceback (most recent call last):
  File "c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\src\utils\error_handling.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\app.py", line 115, in train_models
    model_manager.train_models_for_all_devices(data_path, model_type='random_forest', optimize=optimize)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\src\models\model_manager.py", line 40, in train_models_for_all_devices
    X_train, X_test, y_train_dict, y_test_dict, preprocessor = process_raw_data(
                                                               ~~~~~~~~~~~~~~~~^
        csv_path, save_processed=True
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\src\data_processing\preprocessing.py", line 440, in process_raw_data
    return processor.process_data(csv_path, save_processed, output_dir)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ndr20\Desktop\b.tasarım\smart-home-automation\src\data_processing\preprocessing.py", line 394, in process_data
    df = self.read_data(csv_path)
         ^^^^^^^^^^^^^^
AttributeError: 'SmartHomeDataProcessor' object has no attribute 'read_data'. Did you mean: 'load_data'?

2025-05-27 15:41:08,801 - AkilliEvOtomasyonu - ERROR - Uygulama hatası: Beklenmeyen hata: 'SmartHomeDataProcessor' object has no attribute 'read_data'
